# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ContosoAir

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: contosoair

jobs:
  
  build-and-test:
    name: 🧪 Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['12.x']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: contosoair
        path: ${{github.workspace}}

  Linter:
    name: 🧹 Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    needs: [Prettier, build-and-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          VALIDATE_MARKDOWN: false
          JAVASCRIPT_DEFAULT_STYLE: prettier
  
  Prettier:
    name: 🧹 prettier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,md}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  webapp-deploy:
    name: 📦 Webapp Deploy - sandbox
    runs-on: ubuntu-latest
    needs: [build-and-test, Prettier]
    environment: 
      name: Sandbox
      url: "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
    steps:
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: contosoair
        path: ${{github.workspace}}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.WEB_APP_PUB_PROFILE }}
  
  validate-site:
    name: ✅ Validate Deployment
    runs-on: ubuntu-latest
    needs: webapp-deploy
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net
          follow-redirect: no 
          max-attempts: 3
          retry-delay: 5s 
